[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "foodcast"
version = "0.1.0"
description = "Forecasting and visualization tools for restaurant food sales."
readme = "README.md"
authors = [
    { name = "Jared Winslow"},
]
requires-python = ">=3.9"